preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 60 # in cm
    distance: 172.06  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Fixation duration: 0 # time in s in which the fixation dot is presented
    Fixation ready duration: 0.4 # be ready for the stimulus to come
    Stimulus duration: 0.1 # time in s in which the figure stimulus is presented
    Response window: [1.2, 1.6] # duration, drawn randomly in this range
    Buttons: ['4', '2'] # first is lower second is upper
    Break buttons : ['b'] # what button to press to continue the experiment after a break
    Line lengths : [4 , 4, 4, 4, 4, 4, 4] # [6, 7, 8, 9, 10, 11, 12]
    Line widths : [2.4, 2.6, 2.8, 3, 3.2, 3.4, 3.6] # [3, 3, 3, 3, 3, 3, 3]
    Line orientations : [1, 2, 3, 4] # possible orientations (this is according to the filenames! NOT in degrees!)
    Line spacing : [3.82, 3.98, 4.14, 4.3, 4.46, 4.62, 4.78] # [5, 5, 5.5, 6, 6.25, 6.5, 6.8]
    Position noise : [4, 4, 4, 4, 4, 4, 4, 4] # [5, 8, 7, 6, 7, 7, 7]
    Stimulus size : 15.951 # in degrees 
    Number of trials : 20 # this is per condition (per line length)
    No figure trials : 0.15 # the amount of trial without figure (percentage, must be float)
    Figure trials : 0.7 # together with no figure trials must sum up to 1
    Boarder figure trials : 0.15
    Repetitions : [12, 12] # figure/no_figure repetition of same trial type (just the lines are a little differently positioned)
    Blocks : 3
    Break duration: 1000 # duration in s
    After break duration: 1 # this is so that the participant can get ready before the trial continues
    Stimulus path: './stimuli/figs_pilot_3/'
    Screenshot: False # makes a screenshot when aborting experiment
    Exit key: 'q'
    Monitor refreshrate: 60 # in Hz (check readme for explaination)
    Screentick conversion: 30 # The value used to calculate how many screenticks there are per frame (check Readme for how we use the term 'frame')
