preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1536, 864] # [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 29.4 # 69.8  # in cm
    distance: 70 # 210  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Fixation duration: 0.3 # time in s in which the fixation dot is presented
    Stimulus duration: 0.3 # time in s in which the figure stimulus is presented
    Response window: 1.2 # or 2.2? time in s 
    Line lengths : [2, 4, 8, 10, 14, 16]
    Line orientations : [45, 135] # possible orientation in degrees
    Number of trials : 10 # this is per condition (per line length)
    Break duration: 3 # duration in s, TODO: NOT SURE IF WE WILL HAVE BREAKS
    Stimulus path: './stimuli/'
    Screenshot: False # makes a screenshot when aborting experiment
    Exit key: 'q'
